### ISSUE TITLE
Error after scan qr code

### ISSUE THREAD

**Issue by Aldisetiawan14** [Ramlan404/babybot#5]
TypeError: Cannot read properties of undefined (reading 'toString')
    at WAConnection.base64EncodedAuthInfo (/data/data/com.termux/files/home/XinzBot/node_modules/@adiwajshing/baileys/lib/WAConnection/0.Base.js:126:42)
    at start (/data/data/com.termux/files/home/XinzBot/main.js:2:18426)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
node:internal/errors:465
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be of type string or an instance of ArrayBuffer, Buffer, TypedArray, DataView, KeyObject, or CryptoKey. Received undefined
    at new NodeError (node:internal/errors:372:5)
    at prepareSecretKey (node:internal/crypto/keys:580:11)
    at Cipheriv.createCipherWithIV (node:internal/crypto/cipher:133:9)
    at new Cipheriv (node:internal/crypto/cipher:243:3)
    at Object.createCipheriv (node:crypto:143:10)
    at Object.aesEncrypt (/data/data/com.termux/files/home/XinzBot/node_modules/@adiwajshing/baileys/lib/WAConnection/Utils.js:108:24)
    at WAConnection.sendBinary (/data/data/com.termux/files/home/XinzBot/node_modules/@adiwajshing/baileys/lib/WAConnection/0.Base.js:321:26)
    at WAConnection.<anonymous> (/data/data/com.termux/files/home/XinzBot/node_modules/@adiwajshing/baileys/lib/WAConnection/4.Events.js:86:18)
    at WAConnection.emit (node:events:539:35)
    at WAConnection.emit (/data/data/com.termux/files/home/XinzBot/node_modules/@adiwajshing/baileys/lib/WAConnection/4.Events.js:664:41) {
  code: 'ERR_INVALID_ARG_TYPE'
}

**Comment by Ramlan404** [comment]
Jangan menggunakan beta/multi device pak
